# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
permissions:
  contents: write
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./src
    - name: Publish linux
      run: dotnet publish --configuration Release --output ./publish/linux --runtime linux-x64 --single-file true
      working-directory: ./src
    - name: Publish window
      run: dotnet publish --configuration Release --output ./publish/win --runtime win-x64 --single-file true
      working-directory: ./src

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: ./src/publish
         
        
